#define SSETBIT(WORD,BITPOS) (WORD=(1<<BITPOS))
#define SCLRBIT(WORD,BITPOS) (WORD=(1<<BITPOS))
#define SETBIT(WORD,BITPOS) (WORD|=(1<<BITPOS))
#define CLRBIT(WORD,BITPOS) (WORD&=~(1<<BITPOS))

#define RWBIT(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
#define WBIT(WORD,BITPOS,BIT) WORD=((WORD&~(1<<BITPOS))|(BIT<<BITPOS))


#define WNIBBLE(WORD,STARTBITPOS,NIBBLE) WORD=((WORD&~(15<<STARTBITPOS))|(NIBBLE<<STARTBITPOS))
						 

#define WBYTE(WORD,STARTBITPOS,BYTE) WORD=((WORD&~(255<<STARTBITPOS))|(BYTE<<STARTBITPOS))
						 
#define RBYTE(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&255)

#define RNIBBLE(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&15)

#define RBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)



